#!/bin/sh 
### BEGIN INIT INFO
# Provides:             psplash
# Required-Start:
# Required-Stop:
# Default-Start:        S
# Default-Stop:
### END INIT INF

if grep -qE '\s?psplash=false\s?' /proc/cmdline; then
	echo "Boot splashscreen disabled"
	exit 0;
fi

. /etc/default/splashfuncs
. /etc/default/psplash

case `machine_id` in
    "hp_ipaq_h3100"|"hp_ipaq_h3800") 
	PARAMS='-a 90' ;;
    "hp_ipaq_3600"|"hp_ipaq_3700"|"hp_ipaq_h3900"|"htc_universal"|*collie|*poodle|*akita|*spitz|*borzoi)
	PARAMS='-a 270' ;;
esac

export TMPDIR=/mnt/.splash
mount tmpfs -t tmpfs $TMPDIR -o,size=40k

/usr/bin/psplash $PARAMS &

# Timetrap against hanging with splash hiding console messages.
(sleep 120; psplash-write "QUIT") &
